---
title: "Additional Syllabus Information"
output: 
  html_document:
    toc: true
    doc_depth: 2
    toc_float: true
    theme: cosmo
---

# Doct--Profes--Miste--"Hey, you!"
What should you call me? If this is the first time I've had you in class, I prefer "Professor Roith" ("Dr. Roith" is OK but I might try to perform surgery on you). If I've had you in a previous class, or we are working together regularly (on research, CIR, as a TA, etc.) you may call me "Joe". I typically don't like "Professor Joe" or "Mr. Roith".

As we go through the semester and get to know each other more and have better discussions, I may let everyone call me Joe. I hope we get to that point!

Please feel free to inform me on your preferred name at any time (including immediately after I forget to use it).

# Expectations
During this course I will have many expectations of you. In turn, you should have expectations of me (I encourage you to discuss this with other professors as well, just don't tell them I gave you the idea).

## My expectations of you

* Show up to class.
    * On time and stay the entire time (this includes refraining from packing up with 5 mins left in class).

* Show up to class prepared to learn and discuss.
    * This means complete the reading assignments, homework, or anything else required of you. It also means be engaged, give the topic your full attention (no sleeping).
    
* Be open to statistics. 
    * Find your motivation for using and learning stats, it can be used in *any* field.

* Be persistent.
    * There will be times where you get frustrated with the material or the software. Just know that you are not the first or only one to encounter these issues. Especially in R, remember these two facts: 1) people WAY more advanced than you make stupid mistakes daily in R and 2) people at any level who search for solutions or ask for help usually can get their problems resolved.
    
* Make this a fun, respectful class.
    * I like to joke around and have fun in class. Feel free to join in and feel relaxed, but don't take things too far. I will keep us on task and will not tolerate inappropriate behavior.
    
## Your expectations of me

* I will make this a safe place for learning.
    * Your voice will be heard and is needed as a valid part of the population. I want as many viewpoints as I can get.
    * I will change things if you feel this is not a safe place for learning. It helps me become a better teacher so *please* let me know how I can be more inclusive and open.

* I will show up to class on time every day.
    * If I cannot I will inform you as soon as possible.
    
* I will return graded assignments in a timely fashion (Hopefully within one week of due date).

* I will push you to learn, but slow down when needed.
    * You just need to let me know when things are getting too fast (or slow).
    
* ... what else?


# How to succeed

There have been many studies performed to quantify classroom behavior and course performance at the college level. Here are some resources to help you succeed at the collegiate level.

## Technology
Our subject requires the use of the most current technologies. Computers, cell phones, and tablets are all helpful to collect, manage, and analyze data. However, in our classroom they will be a distraction if not used in accordance to the material at hand. Not only are they a distraction to you, but also to me and your peers. Believe it or not, I actually **can** tell when you are taking snapchat selfies, checking your insta, or even writing that lab report for your biology class. 

Put the phones away, and even consider taking hand written notes during lecture portions of class. [Research](https://www.psychologicalscience.org/news/releases/take-notes-by-hand-for-better-long-term-comprehension.html) has shown that students have better long-term comprehension when taking notes by hand.

## Speak up
I want to get everyone in class to speak at some point during the semester. [More research](http://www.ascd.org/publications/educational-leadership/nov14/vol72/num03/Get-All-Students-to-Speak-Up.aspx) points to the fact that in a typical classroom, about 80 percent of the discussion is lead by 15 percent of students. And when you speak up, you are more likely to achieve a higher grade than when you do not.

I will let there be silence in the classroom until someone talks or I may call on you to give your opinion. The classroom may feel slightly uncomfortable occasionally, but know that this is a safe environment where I invite any question. No one is here to judge what you say in the classroom, we are all learning and new at this.

## Think about the textbook
Don't simply read the textbook. Take time to think about what you read. When learning any subject there are things you know, things you know you don't know, and things you don't know you don't know ( [woah](https://www.youtube.com/watch?v=9CS7j5I6aOc) ). 

[Metacognition](https://cft.vanderbilt.edu/guides-sub-pages/metacognition/) is the process of thinking about how you think. Basically, before you read a chapter, think about what you know about that topic (you my know nothing about it). After you read it, think about what you now understand, and think about how it fits into the larger subject of statistics (this is where I come in to put things in perspective). Finally, understand that there are things you won't understand right away and that's OK. Talk about your areas of confusion in or out of class with me, the SI, a tutor, your dog, just verbalize them and try to find the source of the confusion.

# More academic resources

## Writing

Peer tutors at the Writing Desk offer help with any paper, in any class, at any stage of the writing process. You can sign up for an appointment online or drop in to RML 354 or the outer reference room, across from the reference desk/by the IT helpdesk. Tutors are available Sundays 12-5 and 7-10, Mondays-Thursdays 9-5 and 7-10, and Fridays 9-5. Learn more at [http://wp.stolaf.edu/caas/writing-help/](http://wp.stolaf.edu/caas/writing-help/).

## Speaking

Speaking tutors help students effectively speak and listen within academic conversations, from participating in or leading class discussions to preparing and rehearsing formal presentations. You can sign up for an appointment online or drop in Sundays-Thursdays 7-10pm in RML355. Learn more at [http://wp.stolaf.edu/caas/speaking-center/](http://wp.stolaf.edu/caas/speaking-center/).

## Mental health

I greatly value your experience in this class, and it is my duty to facilitate a safe, caring, and productive learning environment. I recognize that you may experience a range of emotional, physical, and/or psychological issues, both in and out of the classroom, that may distract you from your learning.
If you are experiencing such issues, please do not hesitate to come see me—I am here to listen. We can also discuss what further resources might be available to you.

I take this very seriously. I understand the stress and load you are feeling from other classes and activities. I expect you to do the work in this class and your others but I want you to be *healthy people* above all else.

## Gender Pronouns

This course affirms people of all gender expressions and gender identities. If you go by a different name than what is on the class roster, please let me know. Using correct gender pronouns is important to me, so you are encouraged to share your pronouns with me and correct me if a mistake is made. If you have any questions or concerns, please do not hesitate to contact me.

Statistics has traditionally been a bastion of gender stigmas. We will discuss how we can promote change and also how we sometimes have to deal with the nature of data as collected.